name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main

# Sử dụng bun/setup-bun
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bun/setup-bun@v1
        with:
          bun-version: stable
      - run: bun --version
      - run: bun install
      - run: bun run start

